# 3.2.Software Solución de Sistemas de Ecuaciones
##### Desarrollar una aplicación con un lenguaje de alto nivel para resolver sistemas de ecuaciones lineales y no lineales.

# Métodos Númericos
### Ingeniería en Sistemas Computacionales
### Docente: MM. Jorger Pool Cel
### Equipo:
#### Ché Dzib Héctor Armín
#### Herrera Tuz Adrián Martín
#### Kanxoc Hau Lourdes Judith
### UNIDAD 3
### 4°A

## Para sistemas de ecuaciones lineales

### Método de Gauss-Seidel

In [1]:
import numpy

print ('Introduce el tamaño de la matriz')
m=int(input('Valor de m:'))
n=int(input('Valor de n:'))
matrix = numpy.zeros((m,n))
x=numpy.zeros((m))

vector=numpy.zeros((n))
comp=numpy.zeros((m))
error=[]


print ('Introduce los valores de la matriz')
for r in range(0,m):
    for c in range(0,n):
        matrix[(r),(c)]=float(input("Elemento a["+str(r+1)+str(c+1)+"] "))
    vector[(r)]=float(input('b['+str(r+1)+']: '))
tol=float(input("Digite la tolerancia del error: "))
itera=int(input("Digite el número máximo de iteraciones: "))


k=0
while k<itera:
    suma=0
    k=k+1
    for r in range(0,m):
        suma=0
        for c in range(0,n):
            if (c != r):
                suma=suma+matrix[r,c]*x[c]               
        x[r]=(vector[r]-suma)/matrix[r,r]
        print("x["+str(r)+"]: "+ str(x[r]))
    del error[:]
    for r in range (0,m):
        suma =0
        for c in range(0,n):
            suma= suma+matrix[r,c]*x[c]
        comp[r]= suma
        dif=abs(comp[r]-vector[r])
        error.append(dif)
        print("Error en x[",r,"]= ", error[r])
    print("Iteraciones: ", k)
    if all (i<=tol for i in error) == True:
        break

Introduce el tamaño de la matriz
Valor de m:4
Valor de n:4
Introduce los valores de la matriz
Elemento a[11] 10
Elemento a[12] -1
Elemento a[13] 2
Elemento a[14] 0
b[1]: 6
Elemento a[21] -1
Elemento a[22] 11
Elemento a[23] -1
Elemento a[24] 3
b[2]: 25
Elemento a[31] 2
Elemento a[32] -1
Elemento a[33] 10
Elemento a[34] -1
b[3]: -11
Elemento a[41] 0
Elemento a[42] 3
Elemento a[43] -1
Elemento a[44] 8
b[4]: 15
Digite la tolerancia del error: 0.001
Digite el número máximo de iteraciones: 500
x[0]: 0.6
x[1]: 2.3272727272727276
x[2]: -0.9872727272727273
x[3]: 0.8788636363636363
Error en x[ 0 ]=  4.301818181818183
Error en x[ 1 ]=  3.623863636363641
Error en x[ 2 ]=  0.8788636363636364
Error en x[ 3 ]=  0.0
Iteraciones:  1
x[0]: 1.0301818181818183
x[1]: 2.0369380165289255
x[2]: -1.0144561983471074
x[3]: 0.9843412190082644
Error en x[ 0 ]=  0.23596776859504232
Error en x[ 1 ]=  0.3436162190082612
Error en x[ 2 ]=  0.10547758264462814
Error en x[ 3 ]=  0.0
Iteraciones:  2
x[0]: 1.00658504132231

### Método de Jacobi

In [ ]:
import numpy as np
from math import *

In [7]:
#Definimos la matriz T
T = np.array([[0,1/10,-1/5,0],[1/11,0,1/11,-3/11],[-1/5,1/10,0,1/10],[0,-3/8,1/8,0]])
c = np.array([3/5,25/11,-11/10,15/8])
x = np.array([0,0,0,0]) #vector de valores iniciales
erroraceptado=0.001

In [8]:
import numpy as np
from math import *
print(T.shape)
print(c.shape)
error=1
while error>0.001:
    resultado=np.dot(T,x) + c
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    
    print("Vector resultado: " , resultado)
    x=resultado

(4, 4)
(4,)
Vector resultado:  [ 0.6         2.27272727 -1.1         1.875     ]
Vector resultado:  [ 1.04727273  1.71590909 -0.80522727  0.88522727]
Vector resultado:  [ 0.93263636  2.05330579 -1.04934091  1.13088068]
Vector resultado:  [ 1.01519876  1.95369576 -0.96810863  0.97384272]
Vector resultado:  [ 0.9889913   2.01141473 -1.0102859   1.02135051]
Vector resultado:  [ 1.00319865  1.99224126 -0.99452174  0.99443374]
Vector resultado:  [ 0.99812847  2.00230688 -1.00197223  1.00359431]
Vector resultado:  [ 1.00062513  1.9986703  -0.99903558  0.99888839]
Vector resultado:  [ 0.99967415  2.00044767 -1.00036916  1.00061919]


## Para sistemas de ecuaciones no lineales

### Método de punto fijo

In [9]:
import math

import numpy as np

def f(x):
    return x**3 + x - 6

def g(x):
    return (6-x)**(1/3)

p0=float(input("Ingrese el valor inicial p0: "))
tol=float(input("Ingrese el error: "))
N=int(input("Ingrese el número de iteraciones: "))
i=1
while i<N:
    p=g(p0)
    if abs(p-p0)<tol:
        print("El punto fijo es ",p,"después de ",i, "iteraciones")
        break
    i=i+1
    p0=p
    print('Iteracion: ', p0)
    if i>N:
        print("El método no converge")

Ingrese el valor inicial p0: 1.5
Ingrese el error: 0.0001
Ingrese el número de iteraciones: 50
Iteracion:  1.6509636244473134
Iteracion:  1.6322913532758982
Iteracion:  1.6346240593972983
Iteracion:  1.6343330008665646
El punto fijo es  1.634369322747108 después de  5 iteraciones


### Método de Newtón Raphson

In [10]:
import numpy as np

# INGRESO
fx  = lambda x: x**2 - 6
dfx = lambda x: 2*x

x0 = 1
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 10)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[1.0000000000e+00 3.5000000000e+00 2.5000000000e+00]
 [3.5000000000e+00 2.6071428571e+00 8.9285714286e-01]
 [2.6071428571e+00 2.4542563601e+00 1.5288649706e-01]
 [2.4542563601e+00 2.4494943716e+00 4.7619884713e-03]
 [2.4494943716e+00 2.4494897428e+00 4.6288194135e-06]]
raiz en:  2.4494897427875517
con error de:  4.628819413543539e-06
